/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author zoemariechor
 */

public class lecturerMyAppointment extends javax.swing.JFrame {
    private String lecturerID; 
    
    //Constructor for lecturerMyAppointment class.
    public lecturerMyAppointment(String lecturerID) {
        this.lecturerID = lecturerID; 
        initComponents();
        loadAppointments(); 
    }

    // Method to load booked appointments for the lecturer.
    private void loadAppointments() {
        DefaultListModel<String> model = new DefaultListModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader("consultation.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] details = line.split(",");
                if (details.length >= 6 && details[1].equals(lecturerID) && details[5].equalsIgnoreCase("Booked")) {
                    String studentID = details[2].trim();
                    String studentName = getName(studentID);

                    String appointmentDetails = String.format(
                        "Date: %s, Time: %s, Student: %s (%s)",
                        details[3], details[4], studentName, studentID
                    );
                    model.addElement(appointmentDetails);
                }
            }
        } catch (Exception e) {
            System.err.println("Error loading appointments: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error loading appointments.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        UAListMAL.setModel(model); 
    }

    // Method to get the name of a user (student or lecturer) by their ID.
    private String getName(String userID) {
        String name = "Unknown Student"; 
        File file = new File("user.txt");

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");

                if (parts[0].trim().equals(userID)) {
                    name = parts[1].trim(); 
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading user file.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HistoryButtonUAL = new javax.swing.JButton();
        ResButtonUAL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UAListMAL = new javax.swing.JList<>();
        DBButtonMAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HistoryButtonUAL.setText("History");
        HistoryButtonUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryButtonUALActionPerformed(evt);
            }
        });

        ResButtonUAL.setText("Reschedules");
        ResButtonUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResButtonUALActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Big Caslon", 0, 18)); // NOI18N
        jLabel1.setText("Upcoming Appointments");

        jScrollPane1.setViewportView(UAListMAL);

        DBButtonMAL.setText("Dashboard");
        DBButtonMAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBButtonMALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DBButtonMAL)
                .addGap(18, 18, 18)
                .addComponent(HistoryButtonUAL)
                .addGap(18, 18, 18)
                .addComponent(ResButtonUAL)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistoryButtonUAL)
                    .addComponent(ResButtonUAL)
                    .addComponent(DBButtonMAL))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoryButtonUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryButtonUALActionPerformed
        lecturerAppHistory lecturerAppHistory = new lecturerAppHistory(lecturerID);
        lecturerAppHistory.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_HistoryButtonUALActionPerformed

    private void DBButtonMALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBButtonMALActionPerformed
        lecturerDashboard lecturerDashboard = new lecturerDashboard(lecturerID);
        lecturerDashboard.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_DBButtonMALActionPerformed

    private void ResButtonUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResButtonUALActionPerformed
        lecturerAppReschedule lecturerAppReschedule = new lecturerAppReschedule(lecturerID);
        lecturerAppReschedule.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_ResButtonUALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            String testLecturerID = "LT001"; 
            new lecturerMyAppointment(testLecturerID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBButtonMAL;
    private javax.swing.JButton HistoryButtonUAL;
    private javax.swing.JButton ResButtonUAL;
    private javax.swing.JList<String> UAListMAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
