/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zoemariechor
 */
public class lecturerDashboard extends javax.swing.JFrame {
    private String lecturerID; 

    // Constructor for the lecturerDashboard class.
    public lecturerDashboard(String lecturerID) {
        this.lecturerID = lecturerID; 
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MCButtonLD = new javax.swing.JButton();
        MAButtonLD = new javax.swing.JButton();
        ProfileButtonLDB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Big Caslon", 0, 18)); // NOI18N
        jLabel1.setText("Lecturer Dashboard");

        MCButtonLD.setText("Manage Consultation");
        MCButtonLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCButtonLDActionPerformed(evt);
            }
        });

        MAButtonLD.setText("My Appointments");
        MAButtonLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAButtonLDActionPerformed(evt);
            }
        });

        ProfileButtonLDB.setText("Profile");
        ProfileButtonLDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonLDBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Silom", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("APU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProfileButtonLDB)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MCButtonLD)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(MAButtonLD)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfileButtonLDB)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(MCButtonLD)
                .addGap(18, 18, 18)
                .addComponent(MAButtonLD)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MCButtonLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCButtonLDActionPerformed
        manageConsultation manageConsultation = new manageConsultation(lecturerID); 
        manageConsultation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MCButtonLDActionPerformed

    private void MAButtonLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAButtonLDActionPerformed
        lecturerMyAppointment lecturerMyAppointment = new lecturerMyAppointment(lecturerID); 
        lecturerMyAppointment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MAButtonLDActionPerformed

    private void ProfileButtonLDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonLDBActionPerformed
        profile profile = new profile(lecturerID); 
        profile.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_ProfileButtonLDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            String testLecturerID = "LT001"; 
            new lecturerDashboard(testLecturerID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MAButtonLD;
    private javax.swing.JButton MCButtonLD;
    private javax.swing.JButton ProfileButtonLDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
